import Head from "next/head";
import SideNavbar from "./components/SideNavbar";
import Courses from "./components/Courses";
import News from "./components/News";
import Progress from "./components/Progress";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full h-screen font-monstreat">
        <SideNavbar />

        <div id="container" className="w-full h-screen lg:p-8 sm:p-5 p-3 overflow-scroll lg:pr-36 sm:pr-10 pr-0">
          <Courses />
          <News />
          <Progress />
         
        </div>
      </main>
    </>
  );
}
